-- +goose Up
CREATE TABLE `Posts` (
`PostID` INTEGER NOT NULL AUTO_INCREMENT,
PRIMARY KEY(`PostID`),
`Title` VARCHAR (255) NOT NULL,
`Body` VARCHAR (255) NOT NULL,
`UserID` INTEGER NOT NULL,
`CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`)
) ENGINE=InnoDB;

-- +goose Down
DROP TABLE `Posts`;
