-- +goose Up
CREATE TABLE `Users` (
`UserID` INTEGER NOT NULL AUTO_INCREMENT,
PRIMARY KEY(`UserID`),
`ApiToken` VARCHAR (255) NOT NULL,
`Email` VARCHAR (255) NOT NULL,
`FirstName` VARCHAR (255) NOT NULL,
`LastName` VARCHAR (255) NOT NULL,
`Password` VARCHAR (255) NOT NULL,
`CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- +goose Down
DROP TABLE `Users`;
