package misc

const (
	// ACTION_INDEX
	ACTION_INDEX = "INDEX"
	// ACTION_CREATE
	ACTION_CREATE = "CREATE"
	// ACTION_SHOW
	ACTION_SHOW = "SHOW"
	// ACTION_UPDATE
	ACTION_UPDATE = "UPDATE"
	// ACTION_DELETE
	ACTION_DELETE = "DELETE"
)

// ACTIONS represents list of possible CRUD actions
var ACTIONS = []string{
	ACTION_INDEX, ACTION_CREATE, ACTION_SHOW, ACTION_UPDATE, ACTION_DELETE,
}
