package misc

const (
	ACTION_INDEX  = "INDEX"
	ACTION_CREATE = "CREATE"
	ACTION_SHOW   = "SHOW"
	ACTION_UPDATE = "UPDATE"
	ACTION_DELETE = "DELETE"
)

var ACTIONS = []string{
	ACTION_INDEX, ACTION_CREATE, ACTION_SHOW, ACTION_UPDATE, ACTION_DELETE,
}
